# Generated by Django 5.2.1 on 2025-05-14 21:50

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTechnician',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab Technician Profile',
                'verbose_name_plural': 'Lab Technician Profiles',
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_user_id', models.UUIDField(db_index=True)),
                ('doctor_user_id', models.UUIDField(db_index=True)),
                ('order_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('test_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('sample_collected', 'Sample Collected'), ('testing_in_progress', 'Testing In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='ordered', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab Order',
                'verbose_name_plural': 'Lab Orders',
                'ordering': ['-order_date'],
                'indexes': [models.Index(fields=['patient_user_id', '-order_date'], name='lab_app_lab_patient_94ae6c_idx'), models.Index(fields=['doctor_user_id', '-order_date'], name='lab_app_lab_doctor__a7ff91_idx'), models.Index(fields=['status'], name='lab_app_lab_status_3b7530_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lab_order_id', models.UUIDField(db_index=True)),
                ('lab_technician_user_id', models.UUIDField(db_index=True)),
                ('result_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('result_data', models.JSONField()),
                ('status', models.CharField(choices=[('preliminary', 'Preliminary'), ('final', 'Final'), ('corrected', 'Corrected')], db_index=True, default='final', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab Result',
                'verbose_name_plural': 'Lab Results',
                'ordering': ['-result_date'],
                'indexes': [models.Index(fields=['lab_order_id'], name='lab_app_lab_lab_ord_e30462_idx'), models.Index(fields=['lab_technician_user_id', '-result_date'], name='lab_app_lab_lab_tec_4789df_idx'), models.Index(fields=['status'], name='lab_app_lab_status_77b193_idx')],
            },
        ),
    ]
