# Generated by Django 5.2.1 on 2025-05-15 08:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_user_id', models.UUIDField(db_index=True)),
                ('doctor_user_id', models.UUIDField(db_index=True)),
                ('prescription_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('fulfilled_by_pharmacist_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('fulfilled_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-prescription_date'],
                'indexes': [models.Index(fields=['patient_user_id', '-prescription_date'], name='prescriptio_patient_bfdf65_idx'), models.Index(fields=['doctor_user_id', '-prescription_date'], name='prescriptio_doctor__acfebe_idx'), models.Index(fields=['status'], name='prescriptio_status_ecc272_idx'), models.Index(fields=['fulfilled_by_pharmacist_user_id'], name='prescriptio_fulfill_73ef95_idx')],
            },
        ),
    ]
