# Generated by Django 5.2.1 on 2025-05-14 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_user_id', models.UUIDField(db_index=True)),
                ('doctor_user_id', models.UUIDField(db_index=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('noshow', 'No Show')], default='booked', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'indexes': [models.Index(fields=['doctor_user_id', 'start_time', 'end_time'], name='appointment_doctor__a8d987_idx'), models.Index(fields=['patient_user_id', 'start_time', 'end_time'], name='appointment_patient_679bda_idx'), models.Index(fields=['status'], name='appointment_status_019d5a_idx')],
            },
        ),
    ]
