# Generated by Django 5.2.1 on 2025-05-15 07:58

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_user_id', models.UUIDField(db_index=True)),
                ('doctor_user_id', models.UUIDField(db_index=True)),
                ('report_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor Report',
                'verbose_name_plural': 'Doctor Reports',
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['patient_user_id', '-report_date'], name='medical_rec_patient_6b2ed0_idx'), models.Index(fields=['doctor_user_id', '-report_date'], name='medical_rec_doctor__07f000_idx')],
            },
        ),
    ]
